version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"  # The location of the composer.json file (root directory)
    schedule:
      interval: "weekly"  # Can be "daily", "weekly", or "monthly"
